title: Digital Resume/CV
description: Results-driven software engineer with strong problem solving skills and 10+ years of experience executing innovative solutions to enhance productivity or user experience within time and budget constraints.
theme: jekyll-theme-time-machine
